
version: '3'

services:

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    image: nginx
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - 443:443
    restart: always
    networks:
      - inception
    
  wordpress:
    container_name: wordpress
    depends_on:
      - maria_db
    image: wordpress:6-fpm
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - 9000:9000
    restart: always
    networks:
      - inception

  maria_db:
    container_name: maria_db
    image: mariadb
    ports:
      - 3036:3036
    restart: always
    volumes:
      - db_vol:/var/lib/mysql
    networks: 
      - inception
    env_file:
      - .env

networks:
  inception:

volumes:
  wordpress_vol:
  db_vol:
